kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.0
clusterName: k8s-master
dns:
  type: CoreDNS
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.1.0.0/16"
  dnsDomain: "cluster.local"
controlPlaneEndpoint: "{{ node_ip }}:6443"
apiServer:
  certSANs:
  - {{ node_ip }}
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
